[[Libuuid]]
arch = "aarch64"
git-tree-sha1 = "b29fe86a77e3eeffe49d894d089ccd614c864cc3"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "c75f1292bd74ca6303b758cc61e87e37a5def4c0e45889d20fab7e94b976f821"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.41.3+0/Libuuid.v2.41.3.aarch64-linux-gnu.tar.gz"
[[Libuuid]]
arch = "aarch64"
git-tree-sha1 = "b9c1fdcee7971375a010f96a47fea00a9a1f334c"
libc = "musl"
os = "linux"

    [[Libuuid.download]]
    sha256 = "329d58bde0395e75bcc090baabfb271bd979bc4791958af139bc86ef4237967b"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.41.3+0/Libuuid.v2.41.3.aarch64-linux-musl.tar.gz"
[[Libuuid]]
arch = "aarch64"
git-tree-sha1 = "903929a67f4d72e762474fe806ac414edcbc7fbe"
os = "freebsd"

    [[Libuuid.download]]
    sha256 = "dc25c1b3ae97c7bb4dfc067278713f2532f7a1d199202f99fb90ea2c28cc3484"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.41.3+0/Libuuid.v2.41.3.aarch64-unknown-freebsd.tar.gz"
[[Libuuid]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4d66940e2802f3f459f02d49a19714d3608d5a06"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "797d99494e74e959c53d35911baf1e3ae8e99785988a5432ed43a0e2f3788aee"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.41.3+0/Libuuid.v2.41.3.armv6l-linux-gnueabihf.tar.gz"
[[Libuuid]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ec8358c9e716afe40bd42b8cc1504a08a7f9f8a8"
libc = "musl"
os = "linux"

    [[Libuuid.download]]
    sha256 = "c1fd7ca6b61ae59b02e2fde4bf1a427cc1d6b728807d5064f311b1c44f83331f"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.41.3+0/Libuuid.v2.41.3.armv6l-linux-musleabihf.tar.gz"
[[Libuuid]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eff699c04fae7103b935fd4ad14dcbf2e86bb0fb"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "660089a0eabd9a62b61b93822754cb3f1839285b60198e953e98530eb2f886fc"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.41.3+0/Libuuid.v2.41.3.armv7l-linux-gnueabihf.tar.gz"
[[Libuuid]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b0fb19cce0b090dd7e3060bda59702ade213679f"
libc = "musl"
os = "linux"

    [[Libuuid.download]]
    sha256 = "6c498da325b9a5cb735544d7f1e88c3c7eb85e1b046e899ee8d0652a2270672a"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.41.3+0/Libuuid.v2.41.3.armv7l-linux-musleabihf.tar.gz"
[[Libuuid]]
arch = "i686"
git-tree-sha1 = "6e17b55087d762a6e2bd150ac3a339c5e1ea2f43"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "fa31b3f9a7c4f58e83338cbd063306ab848bd2a4b7d672aa9a6e3f53acccf740"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.41.3+0/Libuuid.v2.41.3.i686-linux-gnu.tar.gz"
[[Libuuid]]
arch = "i686"
git-tree-sha1 = "836e80707beba90c00c2ec36aeca139dc40d6f73"
libc = "musl"
os = "linux"

    [[Libuuid.download]]
    sha256 = "202e8685f42b51ca96712322360d6e73696aa41bd31679b0eb6a3707dbe40791"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.41.3+0/Libuuid.v2.41.3.i686-linux-musl.tar.gz"
[[Libuuid]]
arch = "powerpc64le"
git-tree-sha1 = "94abdcfaf83110fcae454f09372cbe8943d15ab0"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "00b75c15ab99986b99753764f501f856a65b1a2ba4233279ef395f5964512f15"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.41.3+0/Libuuid.v2.41.3.powerpc64le-linux-gnu.tar.gz"
[[Libuuid]]
arch = "riscv64"
git-tree-sha1 = "ac32d9b430454392e22a68f5e88c798535668d61"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "5a323e54935186fea2949ec10279e5119bc0843494bb759eebabf577071a3203"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.41.3+0/Libuuid.v2.41.3.riscv64-linux-gnu.tar.gz"
[[Libuuid]]
arch = "x86_64"
git-tree-sha1 = "d4eb9097583273c81405f19b4862d730021574c5"
libc = "glibc"
os = "linux"

    [[Libuuid.download]]
    sha256 = "7a45ab115aa73809d1a2a142453782d08bb2489a8f132355d201e628453f4754"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.41.3+0/Libuuid.v2.41.3.x86_64-linux-gnu.tar.gz"
[[Libuuid]]
arch = "x86_64"
git-tree-sha1 = "dbab870dca9c9c44637d89e08f9052919e88b580"
libc = "musl"
os = "linux"

    [[Libuuid.download]]
    sha256 = "a0819ae71e9e150f222309ef79ae133ffc61873c427b9de43e70ea9fbc548e22"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.41.3+0/Libuuid.v2.41.3.x86_64-linux-musl.tar.gz"
[[Libuuid]]
arch = "x86_64"
git-tree-sha1 = "8c704463c2f2dcf9f599711fa0c35c9ae4219840"
os = "freebsd"

    [[Libuuid.download]]
    sha256 = "91f0dab1b80ca4d1f8e3e40712912649a07f3f523b75caf8cefaf93ecbe1ecb9"
    url = "https://github.com/JuliaBinaryWrappers/Libuuid_jll.jl/releases/download/Libuuid-v2.41.3+0/Libuuid.v2.41.3.x86_64-unknown-freebsd.tar.gz"
